apiVersion: v1
kind: Service
metadata:
  name: customer-service-portal
  namespace: staging
  labels: 
    app: customer-service-portal
spec:
  type: ClusterIP
  selector:
    app: customer-service-portal
  ports: 
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
