apiVersion: v1
kind: ServiceAccount
metadata: 
  name: customer-service-portal-sa
  namespace: staging
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
