apiVersion: kustomize.config.k8s.io/v1beta1
kind:  Kustomization
 
namespace: staging

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/serviceaccount.yaml
  - ../../base/deployment.yaml
  - ../../base/service. yaml
  - ../../base/ingress.yaml
  - ../../base/network-policy.yaml
  - ../../base/hpa.yaml

commonLabels:
  environment: staging
 
images:
  - name: ACR_LOGIN_SERVER/customer-service-portal
    newTag: latest
